blocksds/libnds

include/nds/arm9/keyboard.h, source/arm9/keyboard.c
* Use 16-bit instead of 32-bit keymap indices.
* The only used indices, in practice, are a small set of values < 0 (DVK_* defines) and values 0-255 (the range of a `char`). Given that the DS's bottom display doesn't even have 65536 pixels total, 16-bit should be more than enough.
* This saves 640 bytes of ROM space for the default keyboard.
* Remove unused key buffer if NO_DEVOPTAB is defined.
* The key buffer is only used if `keyboardRead` is present, which is not used alongside libsysnds (which prefers `keyboardUpdate`). As such, it is removed, removing backspace functionality in edge cases but saving ~260 bytes of RAM.
* Resolve bounds check TODO, and fix a bug in handling non-32-wide keymaps while at it.
=> keyboard improvements

source/arm7/input.c
Comes with the benefit of not handling an un-needed variable! 🎉
Backport of https://github.com/DS-Homebrew/TWiLightMenu/commit/98982d74826b490353e34ba3b683ca915bc9c149
=> Remove frame-delay

include/nds.h, include/nds/dma.h, include/nds/ndma.h, include/nds/system.h
This may help you start adding NDMA integrations to DSi-specific things. Also fixes a minor macro bug in `dma.h`. Tried to hold to existing naming conventions, especially in `ndma.h`.
=> add SCFG/NDMA register definitions

source/common/cardEeprom.c
I see you already merged 9cb70adbe72222db8afc25bfc2ac5e24c2f4c8c0, but not this yet so figured I'd open a PR so I could add some notes
Original GodMode9i PRs:
- Line 82: DS-Homebrew/GodMode9i#88 -- fixes dumping 128 KiB EEPROMs (specifically Pokémon Mystery Dungeon: Explorers of Sky)
- Lines 100-181: DS-Homebrew/GodMode9i#79 -- fixes incorrect size detection when the first word was `00000000` because it inverted the number and treated `FFFFFFFF` as a stop condition iirc
- Improved in: DS-Homebrew/GodMode9i#94 -- improves on the previous fix by checking two separate values, to remove the chance of a save ever coincidentally perfectly matching our check value
=> Fix several EEPROM bugs

source/common/cardEeprom.c
Per @asiekierka's comments after #9 was merged, I've added a size limit of 8 MB (the largest DS EEPROM save, Art Academy) and changed it to only check powers of two. Per [melonDS's save DB](https://github.com/melonDS-emu/melonDS/blob/master/src/ROMList.h) non-power of 2 EEPROMs do not exist.
I've tested a handful of games using GM9i and it appears to work as before.
=> More EEPROM improvements

include/nds/interrupts.h, source/arm7/clock.c, source/common/interrupts.c
* Do not provide ARM7/ARM9-specific definitions on the other CPU.
* Add definitions for (most) DSi-specific interrupts.
* Add IRQ_DMA and IRQ_NDMA, to match IRQ_TIMER.
* Increase the size of the main IRQ table and decrease the size of the auxillary IRQ table to match newly required counts.
* Actually initialize the auxillary IRQ table to match the main IRQ table.
* Add IRQ_RTC synonym to replace IRQ_NETWORK. [Personal pet peeve](https://github.com/asiekierka/uxnds/issues/3), it led to confusion when working with ARM7 code. Would benefit from a matching replacement in the default ARM7 examples.
Untested; might benefit from a quick power-on test on a DSi to see if it still boots fine.
=> interrupts: add DSi interrupts, code improvements

include/nds/cothread.h, source/arm9/libc/fatfs/ff.c, source/arm9/libc/fatfs/ffconf.h, source/arm9/libc/fatfs/ffsystem.c
This will avoid filesystem corruption if two cothreads try to write to the filesystem at the same time.
=> fatfs: Implement re-entrancy protection.

include/sys/statvfs.h, source/arm9/libc/fatfs/ff.c, source/arm9/libc/filesystem.c, source/arm9/libc/statvfs.c
Used by NitroTracker.
Also added `int fd` guards to more functions.
=> fatfs: Add statvfs() and fstatvfs() support.

include/nds/arm7/clock.h, include/nds/arm7/i2c.h, include/nds/arm7/input.h, include/nds/arm7/sdmmc.h, include/nds/arm7/serial.h, include/nds/ndma.h, include/sys/statvfs.h, source/arm7/camera.twl.c, source/arm7/input.c, source/arm7/touch.c, source/arm9/libc/statvfs.c, source/arm9/peripherals/camera.twl.c
This allows adding a way to use `inputGetAndSend()` while suppressing lid sleep for advanced users (f.e. during critical operations), without having to copy-paste a bunch of code.
=> arm7: add inputSetLidSleepDuration(), fix C++ guards, KEYXY defines cleanup, document arm7/input.h functions

include/nds/arm9/image.h, include/nds/arm9/pcx.h, source/arm9/image.c, source/arm9/libc/fatfs.c, source/arm9/libc/fatfs/ffconf.h, source/arm9/libc/fatfs/ffsystem.c, source/arm9/pcx.c
* image, pcx: fix missing checks, use bools, unify error checking approach - I spotted this one by looking at the commit history; just a minor improvement.
* fatfs: inline ff_memalloc/ff_memfree - they're just wrappers to malloc/free, so why not?
* fatfs: fix memory leak in fatInit() - these two issues have been spotted by using GCC 12's `-fanalyzer` static analyzer.
=> image, pcx, fatfs: minor fixes

Makefile, Makefile.teak, include/nds.h, include/nds/arm9/teak/dsp.h, include/nds/arm9/teak/tlf.h, include/nds/memory.h, include/nds/nwram.h, include/nds/system.h, include/teak/apbp.h, include/teak/cpu.h, include/teak/icu.h, include/teak/teak.h, include/teak/types.h, source/arm9/teak/dsp.twl.c, source/arm9/teak/process.ctwl.c, source/arm9/teak/utils.twl.s, source/common/nwram.twl.c, source/teak/apbp.c, source/teak/cpu_asm.s, source/teak/icu.c
libteak is a prototype library that can be used to develop binaries to be run in the DSP of the DSi. It requires ARM9 support, which is also added in this commit.
=> teak: Add libteak and ARM9 teak support

source/arm9/libc/fatfs/ff.c, source/arm9/libc/fatfs/ff.h, source/arm9/libc/filesystem.c, source/arm9/libc/nitrofs.c
As per [POSIX specifications](https://pubs.opengroup.org/onlinepubs/009695299/basedefs/sys/stat.h.html), 
>The st_ino and st_dev fields taken together uniquely identify the file within the system.
This PR implements that for FAT and NitroFS filesystems as such:
* For FAT filesystems, `st_dev` is 0 (DLDI) or 1 (DSi SD), while `st_ino` is the starting cluster of the file;
* For NitroFS filesystems, `st_dev` is 2, while `st_ino` is the unique ID of the file within the `.nds` file.
I believe it to be unwise to document the exact meaning of these values outside of code, as users should not rely on them.
Whether this should be merged or not, I'm not too sure; it *does* resolve https://github.com/blocksds/sdk/issues/85 , but I don't think code should be relying on this... But here it is, anyway.
=> fatfs, nitrofs: properly populate st_dev and st_ino

source/common/ndsabi/coroutine.s
Saves one cycle and 4 bytes per occurence.
=> ndsabi: use BLX opcode for coroutine jumps on ARM9

include/nds/bios.h
This uses a technique introduced by @felixjones in gba-hpp to inline BIOS SWI calls.
These specific ones aren't used *too* commonly in practice, but hey - a win's a win. However, testing with programs that make use of them (such as LZ/Huffman compression, math routines, etc) are required before merging.
=> bios: inline BIOS SWI calls

source/arm9/libc/nitrofs.c
Let us never speak of this again.
=> nitrofs: fix file traversal not working without running a chdir() first

include/nds/arm7/serial.h, source/arm7/firmware.c
This is a helper function to read the flash JEDEC values.
A use case for this function is to retrieve the size of the flash; this can be useful in verifying internal hardware, or verify the size of the flash before doing a read of the entire device.
=> firmware: add readJEDEC()

source/arm9/libc/nitrofs.c
This is unlikely to be hit in production, and so doesn't warrant an 0.10.3.
=> nitrofs: fix missing fclose() if pointed to NitroFS-less .nds file

source/arm9/libc/fatfs/ff.c
This allows reading in units larger than one cluster (4KB on smaller cards, up to 32KB if the user manually requests it). For the 4KB case, this gets read speed up from 5.9 MB/s to 7.3 MB/s on my tests with the experimental picolibc patches. 7.3 MB/s is close to the DSi's theoretical bus speed, and likely to be very close to the practical TMIO speed limit; there's also latency overhead of the libc/FatFS stack, as well as latency overhead of the SD card itself, to take into account.
=> fatfs: Support batching contiguous cluster reads.

include/fat.h, include/filesystem.h, source/arm9/libc/fatfs.c, source/arm9/libc/fatfs/ffconf.h, source/arm9/libc/filesystem.c, source/arm9/libc/nitrofs.c
This adds a *significant* speed boost to random accesses; as FAT clusters are stored as an unpacked linked list (so one linked list jump per 4KB cluster), seeking, especially backwards, takes a very long time for larger files. We mitigate this somewhat with the sector cache, but this is a proper fix.
FF_USE_FASTSEEK (exposed via `fatInitLookupCache()`) creates a packed (one linked list jump per non-contiguous cluster) linked list as a cache, making seeks *much* cheaper (no filesystem call, much smaller table to traverse).
After discussing with Gericom, it appears that even for large files, so long as they are lightly/not fragmented, the FASTSEEK buffer size can be measured in the hundreds of bytes. In addition, NitroFS accesses often rely on large backwards/forwards seeks across the file …
=> fatfs: add fatInitLookupCache() to expose FF_USE_FASTSEEK

include/nds/asminc.h, source/common/ndsabi/memcpy.s, source/common/ndsabi/memset.s
Regressed in https://github.com/blocksds/libnds/commit/634499db828284a5c372d38cda05946b245a90b2
Not every function can live in a distinct section. In some cases, there's a deliberate fallthrough - this fixes the issue.
=> ndsabi: fix memcpy/memset regression

include/nds/arm9/camera.h, source/arm9/peripherals/camera.c, source/arm9/peripherals/camera.twl.c
No worries, does not justify a new release - but it does match existing libnds behaviour to check for this.
=> camera: Wrap functions to prevent crash in NDS mode

include/nds/ndstypes.h, source/arm9/system/cache.c, source/common/interrupts.c
* Place code and data in distinct sections. They receive different section flags, which can be handled by the GNU linker, but not by GCC itself - so for the annotations to work properly for LTO code (even if libnds itself is not compiled using LTO), they must name distinct sections.
* Add `__attribute__((noinline))` to functions which use assembly specific to ARM mode - otherwise, attempting to inline them across translations units into Thumb code will cause a compile error.
=> cache, interrupts, types: link-time optimization fixes

include/filesystem.h, source/arm9/libc/dirent.c, source/arm9/libc/fatfs/ff.c, source/arm9/libc/nitrofs.c, source/arm9/libc/nitrofs_internal.h
* Dot and dot-dot entries are now properly emitted in readdir(). In line with common software expectations, they mirror standard FAT filesystem behaviour, that is are present for all subdirectories. For NitroFS, these entries are emulated accordingly.
* The "d_ino" field in readdir() output is now correctly populated, to match stat() and fstat().
* New functions: `nitroFSOpenById()`, `nitroFSFopenById()`. These allow opening a file by its FAT table ID directly, skipping the cost of any required directory lookups.
* Allow opening NitroFS filesystems which only have a FAT table, but no FNT table, using the above API.
I wasn't sure whether to consider https://github.com/blocksds/sdk/issues/69 a bug or not, but @LunarLambda's analysis makes it clear that despite POSIX saying otherwise, the …
=> filesystem: general improvements

source/arm9/libc/dirent.c
`readdir()` should set the index to `INDEX_END_OF_DIRECTORY` when it hits the end of a directory, not `INDEX_NO_ENTRY`. This incorrect index caused a behavior where calling `seekdir()` after hitting the end of the directory would then cause it to attempt to read past the end of the directory, fail, and act as if you had just called `rewinddir()` instead.
=> libc: fix bug in readdir()

include/fat.h, source/arm9/libc/filesystem.c, source/arm9/libc/nitrofs.c, source/arm9/libc/nitrofs_internal.h
This is done for compatibility with libfat. It may be useful in some situations.
Note that in NitroFS it is only possible to get file attributes, as it is a read-only filesystem.
=> fat: nitrofs: Implement get/set FAT file attribute functions

include/machine/_types.h, include/sys/dirent.h
I created a new `sys/dirent.h` by deleting the old one and writing a new one based on [the POSIX specification](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/), as well as [the GNU libc manual](https://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html) and other manuals for BSD/GNU-specific extensions.
This PR means we can finally remove the last disputed bit of BSD/MIT-style licensing. This PR also fixes some minor issues, including but possibly not limited to:
- `d_ino` is now properly documented, and its (and `d_off`)'s sizes are controlled by us (in `machine/_types.h`) to match BlocksDS's requirements,
- `MAXNAMLEN` is now set to the correct maximum value that FatFS can output.
=> include: rewrite sys/dirent.h, fix minor issues

include/nds/arm9/math.h, source/arm9/math.c
Result should be bit-for bit identical to sqrtf from the standard math library, but runs 4x faster.
Currently doesnt handle subnormals (Numbers smaller than 2^-126, e.g. 0.9*2^-127, are called subnormal because they don't follow the standard floating point format, which messes up the math, will add this to the warning.)
Typically subnormal numbers are disabled via -ffast-math anyway.
=> Add hardware accelerated floating point squareroot

Makefile.arm7, Makefile.arm9, source/common/libc/exit.c
I have checked the resulting ELFs, but haven't actually tried to smash the stack - however, I followed the ideas of `retarget_lock_crash`.
(Stack smash protection will work in *non*-debug variants, too, albeit without libnds functions themselves being protected.)
=> libc: Add support for stack smash canaries in debug variants.

include/nds.h, include/nds/arm7/clock.h, include/nds/arm7/codec.h, include/nds/arm7/firmware.h, include/nds/arm7/serial.h, include/nds/arm7/touch.h, include/nds/arm7/tsc.h, include/nds/arm9/video.h, include/nds/registers_alt.h, include/nds/system.h, include/nds/touch.h, source/arm7/clock.c, source/arm7/codec.twl.c, source/arm7/firmware.c, source/arm7/input.c, source/arm7/libnds_internal.h, source/arm7/microphone.c, source/arm7/spi.c, source/arm7/touch.c, source/arm7/touchFilter.c, source/arm7/tsc.c, source/arm7/userSettings.c
- Rewrote touch code.
- A shared, from-scratch measurement filtering routine is now used for both TSC (NTR) and CDC (TWL) touch inputs.
- On TSC, tscMeasure() uses the 16-clock-per-conversion method to speed up measurement readouts.
- On both TSC and CDC, critical section code has been reduced to exclude post-measurement filtering, improving ARM7 responsiveness.
- Added helper SPI_TARGET defines and spiRead, spiWrite, spiExchange functions to clean up SPI communication code.
- Renamed SerialWaitBusy to spiWaitBusy to match.
- Cleaned up microphone input code to use tscRead().
- Various header cleanups:
- Firmware flash commands have been documented in firmware.h, which was split out from serial.h.
- NTR touch screen controller commands have been documented in tsc.h, which was split out …
=> arm7: Rewrite touch code, refactor SPI, RTC code

include/nds/interrupts.h, source/common/interruptDispatcher.s, source/common/interrupts.c
- Constant-time IRQ lookups (always faster on ARM9, faster for second IRQ onwards on ARM7)
- Reduced IRQ table size (saves 128 bytes on ARM9, 188 bytes on ARM7)
Also fixes a bug in `irqClearAUX`.
=> interrupts: new dispatcher

include/nds/arm9/console.h, include/nds/bios.h, source/arm9/console.c
- Remove the convertSingleColor option. This should be done by your preferred asset conversion tool, such as Grit; in addition, we migrated to a proper 1bpp font a while ago for libnds itself.
- Use BIOS bit unpack routines instead of a custom one to handle font decompression.
- Always initialize the palette when an user palette is not provided.
- Add partial support for 2bpp fonts.
=> console: clean up consoleLoadFont()

include/nds.h, include/nds/decompress.h, source/arm9/grf.c, source/arm9/keyboard.c, source/common/decompress.c
This code is applicable to ARM9 and ARM7 environments, without much in the way of anything that depends on the ARM9 CPU.
=> decompress: move from arm9 to common

include/nds/cothread.h, include/threads.h, source/arm9/libc/threads.c
It's very incomplete, as it only maps those functions of <threads.h> which our cothread/comutex system already implements.
=> threads: add partial implementation of C11 threads API, wrapping cothreads

source/common/interruptDispatcher.s
Alternate approach to https://github.com/blocksds/libnds/pull/110 ; see that PR for notes.
=> interrupts: Do not retrigger self to fix uninitialized AUX IE/IF reads in NTR mode.

include/nds.h, include/nds/rsa.h, source/common/rsa.c
The destination length in swiRSADecryptRAW needs to be a pointer a 32-bit unsigned integer.
The patch also provides documentation for functions, paramaters and structures.
=> rsa: fix RSA functions paramaters

source/common/libc/syscalls.c
The latest updates to picolibc cleaned up headers a little, which means less stuff is implicitly included than before.
=> libc: fix <unistd.h> not being included in syscalls.c

include/nds/arm7/audio.h, include/nds/arm9/sound.h, include/nds/fifomessages.h, source/arm7/audio.c, source/arm9/sound.c
The sound capture can be used to capture the output of sound channels 0 and 2, or the output of the sound mixer to the left or right speakers. The captured audio can be saved to RAM or added to the output of sound channels 1 and 3.
While audio capture isn't as useful as video capture, it's still useful to have a way for users to take advantage of it without too much effort.
Audio capture channel 0 requires sound channel 1 to be active. The sample rate of the capture is taken from the sample rate of playback of channel 1 (so that it can be added to it if required). The same applies to audio capture channel 1 and sound channel 2.
The helpers in this patch only let the user setup the capture registers. Sound channels 1 and 3 must be setup by hand. The user may want to play the captured audio …
=> sound: Add sound capture helpers

source/arm9/libc/nitrofs.c
As a Slot-2 cartridge can have a maximum of 32MB of mapped address space, any .nds file over 32MB is guaranteed not to be fully accessible via this method. In particular, NO$GBA mounts the first 32MB of a .nds file in Slot-2, which caused NitroFS reads over the 32MB limit to be corrupted.
=> nitrofs: Block direct Slot-2 access for >32MB .nds files

include/nds/arm9/sassert.h, include/sys/ucontext.h, source/arm7/libc/filesystem.c, source/arm9/libc/fatfs_internal.h, source/arm9/libc/filesystem.c, source/common/libc/syscalls.c
Note that this works with both current (in-repo) and latest (will be pushed with the next BlocksDS update) picolibc version.
=> include, libc: fix includes for latest picolibc commits

source/arm9/system/initSystem.c, source/arm9/video/video.c
- Engine A was having just as many words cleared as engine B, despite engine B not clearing DISPCNT (due to `videoSetModeSub(0);` below - is this desired?
- `dmaFillWords` requires a multiple of 4; with `0x56`, the final register (`BLDY`) was not being cleared.
- Moved the clearing of VRAM banks E-I to `vramDefault();`, at least for now. Makes more sense for all the VRAM configuration to be in one place, to me - though most of the video configuration decisions don't make all that much sense to me at this stage.
=> initSystem: Fix video register clearing ranges, remove redundant VRAM configuration

include/nds.h, include/nds/arm9/ndsmotion.h, source/arm9/peripherals/ndsmotion.c, source/common/cardEeprom.c
- Use AUXSPICNT macros instead of magic numbers for card SPI operations.
- Use Kionix macros instead of magic numbers for DS Motion Card SPI operations.
- Add motion_get_type() and motion_get_name() to the motion sensor driver.
- Clean up code duplication in the motion sensor driver.
- Fix motion sensor driver bugs:
- Potentially fix DS Motion Card support in DSi mode.
- Fix unnecessary DS card writes on deinitialization.
- Fix analog input access causing unwanted GBA I/O when a DS card is detected.
The DS Motion Card proper may now work in DSi mode, but I don't have one to test; I have tested the MK6/R6, but that one seems to not communicate properly with a DSi/3DS at all.
=> cardEeprom, ndsmotion: clean up, fix bugs

include/nds/arm7/aes.h, include/nds/arm9/cp15_asm.h, include/nds/arm9/video.h, include/nds/card.h, include/nds/cpu_asm.h, include/nds/ndstypes.h, source/arm7/libnds_internal.h, source/arm9/math.c, source/arm9/system/gurumeditation.c, source/arm9/video/sprite.c
* Add an immediate value (0) to `udf` instructions, as it is required for LLVM and optional with GCC
* Fix signed overflow from `1 << 31`
* Proper printf format string in gurumeditation (fixes warnings)
* Change an implicit enum cast to explicit, with a comment explaining why it is valid
The only other error/warning still in LLVM 19 is the following:
```c
libnds/source/common/libc/sbrk.c:43:20: error: variable 'stack_ptr' is uninitialized when used here
heap_end = stack_ptr;
^
libnds/source/common/libc/sbrk.c:25:33: note: initialize the variable 'stack_ptr' to silence this warning
register uintptr_t stack_ptr asm("sp");
^
```
It seems like GCC's `register` keyword is explicitly not intended to be used the way it is in sbrk.
From https://gcc.gnu.org/onlinedocs/gcc/Local-Register-Variables.h …
=> LLVM and undefined behavior fixes

include/nds/arm9/math.h
Changes square root register types to unsigned.
Changes square root helper arguments and return types to unsigned. 
Starts integer square root earlier on repeated calls.
I'm unsure about the second point because it seems to me that it's at least partially intended to use these functions with a signed fixed point type, but it doesn't do any checks for negative numbers and instead just treats it as an unsigned number anyway so having them as a signed type isn't useful.
=> Changes to square root functions

source/arm9/libc/fatfs/cache.c, source/arm9/libc/fatfs/cache.h, source/arm9/libc/fatfs/diskio.c
- Fix cache invalidation not invalidating more than one sector per call.
- Replaced cache algorithm with a simple LRU; appears to perform better with simpler code, but more benchmarking/research should be done.
- Removed the malloc() call in disk_write(), replacing it with "borrowing" a slot from the LRU cache without marking it valid.
- Adjusted disk_read() similarly, so that sectors marked as not to be cached do not generate cache requires.
- Added additional debugging defines to diskio.c.
=> cache, diskio: Optimizations and bugfixes.

include/nds/arm9/videoGL.h, source/arm9/video/videoGL.c
We briefly discussed this over Discord around an hour ago.
This change is necessary to allow allocating a palette while the 3D engine is active without causing VRAM corruption.
I've been using a similar change (as a separate function built with my program) successfully for months, and have tested this change as performing equivalently to my earlier version.
=> Let glColorTableEXT allocate VRAM without filling

include/nds/exceptions.h, include/nds/fifocommon.h, source/arm7/exceptions.c, source/arm9/system/exceptions.c, source/arm9/system/system.c, source/common/libnds_internal.h
This PR adds an exception handler that the user needs to enable. When the exception handler is executed, it saves a crash dump in the IPC shared memory and sends a FIFO message to the ARM9 to notify it so that it can print it (the same way it prints ARM9 crash dumps). Note that the FIFO message is just one packet that is sent without using the FIFO library so that the process is more robust.
It also splits the ARM9 exception handler so that it can reuse the printing code for ARM9 and ARM7 crashes.
=> Add ARM7 exception handler that sends the crash dump to the ARM9

include/nds.h, include/nds/arm7/console.h, include/nds/arm9/console.h, include/nds/fifocommon.h, include/nds/fifomessages.h, source/arm7/console.c, source/arm7/libnds_internal.h, source/arm7/system.c, source/arm9/console.c, source/arm9/system/system.c, source/common/libnds_internal.h
The ARM9 allocates a ring buffer in main RAM. This buffer is passed to the ARM7, which then can start writing text to it. The ARM7 needs to notify the ARM9 when new text is added to the buffer so that the ARM9 can print it and empty the buffer.
The system is connected to the current ARM9 console system, so the output of this console can be any PrintConsole in use by the ARM9. For example, it is possible to start one console on the top screen and let the ARM9 use it while there is another console on the bottom screen that is used to print whatever the ARM7 prints.
A custom versions of `puts()` has been implemented, as well as a minimal version of printf(). ARM7 binaries don't have a lot of space to play with, so it's a generally a bad idea to use the regular printf() there.
It's still …
=> Add initial version of the ARM7 console

include/nds/arm7/console.h
`sys/cdefs.h` is what defines `__printflike`, currently console.h relies on cdefs.h being included beforehand.
=> console: include used headers directly

include/nds/bios.h
This SWI isn't available on DSi, only DS, so it's better to not rely on it at all and use the version that libnds has in source/common/swiSoftReset.s.
=> bios: Use custom version of swiSoftReset() instead of SWI #0

source/arm9/video/videoGL.c
when attempting to unload a texture where the palette is assigned from another texture using glAssignColorTable(), the program crashes.
it seems that there is error when removing palette from texture. palette->connectCount should be checked if its `<= 0` instead
this resolve the issue
=> palette connectCount check

include/nds/interrupts.h, source/arm7/intrwait.s
The old prototype of swiIntrWait() doesn't support the extended interrupts of the ARM7. The prototype of swiIntrWaitAUX() supports the new flags.
However, the old prototype has been kept for compatibility with older code and so that code shared between ARM9 and ARM7 can use the same function.
=> bios: Add new swiIntrWaitAUX() for the ARM7

source/common/utf.c
Fixes this warning when building with LLVM:
```
libnds/source/common/utf.c:95:18: error: variable 'utf8_len' is used uninitialized whenever 'if' condition is false
else if (codepoint <= 0x10FFFF)
^~~~~~~~~~~~~~
libnds/source/common/utf.c:106:29: note: uninitialized use occurs here
for (int i = 0; i < utf8_len; i++)
^
libnds/source/common/utf.c:95:14: note: remove the 'if' if its condition is always true
else if (codepoint <= 0x10FFFF)
^
```
It's a false-positive since the condition is always true, so not a bug.
=> Fix potentially uninitialized variable warning

include/dlfcn.h, include/nds.h, source/arm9/dlfcn.c, source/arm9/dsl.h
This PR implements the `dlopen()` family of functions to load `.dsl` dynamic libraries generated by `dsltool`.
More context and discussion here:
https://github.com/blocksds/sdk/issues/44
=> WIP: dlfcn: Add initial helpers to load dynamic libraries

include/nds/arm7/console.h
Remove a picolibc-ism that has been cleaned up in picolibc 1.8.10, instead use the equivalent GCC attribute.
This shouldn't break building with picolibc 1.8.9, so it can be merged sooner.
=> include: Prepare for picolibc 1.8.10 update

source/arm9/system/exceptions.c
Fixes the following error generated by Clang/Zig:
```c
libnds/source/arm9/system/exceptions.c:32:12: error: format string is not a string literal (potentially insecure)
printf(title);
^
libnds/source/arm9/system/exceptions.c:32:12: note: treat the string as an argument to avoid this
printf(title);
^
```
=> exceptions: fix non-literal format string warning

source/arm9/math.c
Kuratius in the gbadev Discord noticed that this asm statement was missing a memory input constraint, since it reads from the memory pointed to by `a`.
I took a look at it, too, and noticed a couple more things. `volatile` isn't necessary because the statement could be eliminated if its outputs were never used, and the `&` modifiers aren't necessary because the inputs aren't read from after the outputs are written to. I also changed the input's name to match the name of the variable instead of the name of the register it will be kept in.
None of this affects the generated code with the current toolchain, but it is a little more correct.
=> math: correct semantics of asm in normalizef32()

include/nds/arm7/nand_crypto.h, source/arm7/storage/nand_crypto.twl.c, source/arm7/storage/storage_fifo.twl.c
This adds an extra check when the arm9 tries to read/write crypted blocks to the DSi nand, ensuring that a call to `nandCrypt_Init` has been done beforehand (in case the ReadCrypt/WriteCrypt functions are called manually by the program without using fatfs)
=> nand: ensure crypto is initialized when a read/write command is issued
