- source/arm9/keyboard.c
The defaultKeyboard struct includes the default keyboard graphics, totaling over 10 kilobytes of data. With curKeyboard being set to defaultKeyboard by default, any code that called any keyboard-related function (for example, stdin_getc_keyboard, pulled in by fgetc and similar) would end up pulling in the keyboard graphics.
> keyboard: avoid pulling in defaultKeyboard struct if keyboard not used

- include/nds/system.h
- source/arm9/system/system.c
Quick commit to make it easy to disable sleep from ARM9.
> sleep: Add ability for ARM9 to disable sleep

- source/arm9/keyboard.c
Fixes https://github.com/blocksds/sdk/issues/55
> keyboard: properly set scroll on first visible frame

- include/nds/bios.h
- source/common/syscalls.c
Fixes some warnings when using the lib...
> Add const qualifiers for compression methods

- source/arm9/keyboard.c
- source/arm9/libc/iob.c
- Keyboard functions now use cothread-based VBlank waits instead of SWI ones. Notably, this allows cothreads to run concurrently with stdin reads.
- The input buffer functionality has been restored, complete with proper handling of Backspace.
> keyboard: fix cothread and backspace support

- source/arm9/libc/fatfs/ff.c
http://elm-chan.org/fsw/ff/patches.html
> FatFs: update to R0.15p3

- include/nds/arm7/audio.h
- source/arm7/microphone.c
- source/arm7/microphone.twl.c
Seems to be a fairly trivial omission. Also cleaned up some constants a bit.
> microphone: add 16-bit capture on TWL

- include/nds/arm7/i2c.h
- include/nds/arm9/camera.h
- include/nds/system.h
- source/arm7/audio.c
- source/arm7/camerai2c.twl.c
- source/arm7/i2c.twl.c
- source/arm7/spi.c
- source/arm7/system.c
- source/arm9/peripherals/camera.twl.c
https://melonds.kuribo64.net/board/thread.php?pid=6140#6140
> audio, camera, i2c, spi, system: clean up magic constants, document CAM_MCNT/SCFG/I2CCNT bits

- source/arm9/libc/nitrofs.c
- source/arm9/libc/nitrofs_internal.h
https://github.com/blocksds/sdk/issues/94
> nitrofs: add Slot-2 support

- include/nds/arm7/serial.h
- include/nds/system.h
- source/arm7/firmware.c
- source/arm7/userSettings.c
Two fewer SPI bus reinitializations.
> userSettings: minor readFirmware() optimization

- source/arm9/system/mpu_setup.s
Bits 14 and 15 of SCFG_EXT9 and SCFG_EXT7 are R/W, and the loader can set them to any value it wants. This only affects what is physically connected to the bus at addresses 0x0D000000-0x0DFFFFFF (and 0x0C000000-0x0CFFFFFF if we want to run in DS mode, but that's not relevant for this patch).
When SCFG_EXT9 specifies that there are 32 MB of RAM available, a retail DSi has open bus in 0x0D000000-0x0DFFFFFF, and a debugger DSi has additional RAM.
In order to actually detect how much RAM there is, it is required to actually test if it's there. It is required to set the RAM size field of SCFG_EXT9 to 32 MB, and try to write/read from the region where the additional 16 MB would be stored.
Once the size has been determined we can use the MPU to lock down the uncached RAM region (16 MB for …
> mpu: Correctly detect debugger DSi RAM

- source/common/cothread/threads.c
More information can be found as a comment in the newly introduced code.
> libc: Force __retarget_lock functions to be linked in

- source/common/card.c
> card: Align all card reads to 0x200 bytes.

- include/nds/dma.h
- source/arm9/video/videoGL.c
- source/common/card.c
- Added DMA_START_LINE definition.
- Documented DMA_START definitions.
- Fixed DMA_START defines on ARM7.
- glCallList() and cardStartTransfer() now use dmaSetParams().
> dma: minor fixes

- include/nds/memory.h
> Add useful get functions

- source/arm9/peripherals/slot2.c
- source/arm9/peripherals/slot2solar.c
It was very broken. Apologies.
> slot2: fix solar sensor support

- include/nds/arm9/ndsmotion.h
- source/arm9/peripherals/ndsmotion.c
- source/arm9/peripherals/slot1.twl.c
Fixes https://github.com/blocksds/sdk/issues/216 . Requires real hardware validation.
> ndsmotion: Implement support for the retail Motion Pack (ATTiny-based)

- source/arm9/teak/utils.twl.s
https://github.com/blocksds/sdk/issues/226
> teak: add missing UAL marker to ASM file

- include/nds/bios.h
https://github.com/blocksds/sdk/pull/249
> bios.h: add constants for TUnpackStruct flag

- source/arm9/libc/fatfs.c
- source/arm9/libc/fatfs/cache.c
- source/arm9/libc/fatfs/cache.h
- source/arm9/libc/fatfs/diskio.c
- source/arm9/libc/statvfs.c
Found while researching adding file system re-initialization, but these seem valuable enough to PR them a bit early.
> fatfs: Minor improvements and bugfixes

- source/arm9/peripherals/slot2.c
Has to be tested with a real NTR-008.
See https://github.com/blocksds/sdk/issues/288
> slot2: Fix rumble pak misdetection

- include/fat.h
- source/arm9/libc/fatfs/ffconf.h
- source/arm9/libc/filesystem.c
This was a missing API relative to upstream libfat.
> fat: add fatGetVolumeLabel(), fatSetVolumeLabel()
